name: Test Suite

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: [3.8]
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python }}
    - name: Install dependencies
      run: python3 -m pip install tox
    - name: Run linters
      run: tox -vve lint
    - name: Static analysis
      run: tox -vve static
  integration-test-microk8s:
    name: Integration tests (microk8s)
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Get prefsrc
      run: |
        echo "IPADDR=$(ip -4 -j route get 2.2.2.2 | jq -r '.[] | .prefsrc')" >> $GITHUB_ENV
    - name: Setup operator environment
      uses: charmed-kubernetes/actions-operator@main
      with:
        juju-channel: 3.4/stable
        provider: microk8s
        channel: 1.25-strict/stable
        microk8s-addons: "hostpath-storage dns metallb:${{ env.IPADDR }}-${{ env.IPADDR }}"
    - name: Update python-libjuju dependency to match juju version
      # Assuming the dep is given on a separate tox.ini line
      run: sed -E -i 's/^\s*juju\s*~=.+/    juju~=3.4.0/g' tox.ini
    - name: Run tests (edge channel)
      run: tox -e integration
    - name: Dump logs
      if: failure()
      uses: canonical/charming-actions/dump-logs@main