name: Pull Requests

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  pull-request:
    name: PR
    uses: canonical/observability/.github/workflows/bundle-pull-request.yaml@main
    secrets: inherit